name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_kernel:
    name: Build Kernel and Boot Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y android-tools-mkbootimg bc build-essential ca-certificates cpio curl git kmod libssl-dev libtinfo5 python2 sudo unzip wget xz-utils
          sudo ln -sf /usr/bin/python2 /usr/bin/python

      - name: Run Build Script
        run: |
          ./build.sh -b ./build_tmp -o out

      - name: Upload Boot/Recovery Images
        uses: actions/upload-artifact@v4
        with:
          name: boot-images
          path: |
            out/boot.img
            out/recovery.img

  build_system:
    name: Prepare System Image (from OTA)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y img2simg jq sudo wget xz-utils

      - name: Fetch and Prepare OTA
        run: |
          DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
          ./build/fetch-and-prepare-latest-ota.sh "16.04/arm64/android9/devel" "$DEVICE" ota
          mkdir -p out/
          ./build/system-image-from-ota.sh ota/ubuntu_command out

      - name: Upload System Image
        uses: actions/upload-artifact@v4
        with:
          name: system-image
          path: out/system.img
